import { Game } from "../types";

export const nbaGames: Game[] = [
  {
    id: "nba-1",
    league: "nba",
    startTime: "7:30 PM ET",
    status: "in_progress",
    period: "Q3",
    clock: "4:12",
    homeTeam: {
      id: "bos",
      name: "Boston",
      abbreviation: "BOS",
      score: 84,
      players: [
        { id: "p-bos-1", name: "J. Tatum", number: "0", position: "SF", stats: { points: 24, rebounds: 8, assists: 4, steals: 1, blocks: 1, turnovers: 2 } },
        { id: "p-bos-2", name: "J. Brown", number: "7", position: "SG", stats: { points: 19, rebounds: 5, assists: 3, steals: 2, blocks: 0, turnovers: 1 } },
        { id: "p-bos-3", name: "K. Porzingis", number: "8", position: "C", stats: { points: 14, rebounds: 10, assists: 1, steals: 0, blocks: 3, turnovers: 1 } },
        { id: "p-bos-4", name: "D. White", number: "9", position: "PG", stats: { points: 11, rebounds: 3, assists: 6, steals: 1, blocks: 2, turnovers: 0 } },
        { id: "p-bos-5", name: "J. Holiday", number: "4", position: "PG", stats: { points: 8, rebounds: 4, assists: 5, steals: 1, blocks: 0, turnovers: 1 } },
        { id: "p-bos-6", name: "A. Horford", number: "42", position: "C", stats: { points: 5, rebounds: 6, assists: 2, steals: 0, blocks: 1, turnovers: 0 } },
        { id: "p-bos-7", name: "S. Hauser", number: "30", position: "SF", stats: { points: 3, rebounds: 1, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-bos-8", name: "P. Pritchard", number: "11", position: "PG", stats: { points: 0, rebounds: 1, assists: 2, steals: 0, blocks: 0, turnovers: 1 } },
      ],
    },
    awayTeam: {
      id: "mia",
      name: "Miami",
      abbreviation: "MIA",
      score: 79,
      players: [
        { id: "p-mia-1", name: "J. Butler", number: "22", position: "SF", stats: { points: 21, rebounds: 6, assists: 5, steals: 2, blocks: 0, turnovers: 2 } },
        { id: "p-mia-2", name: "B. Adebayo", number: "13", position: "C", stats: { points: 16, rebounds: 11, assists: 4, steals: 1, blocks: 1, turnovers: 3 } },
        { id: "p-mia-3", name: "T. Herro", number: "14", position: "SG", stats: { points: 18, rebounds: 3, assists: 2, steals: 0, blocks: 0, turnovers: 1 } },
        { id: "p-mia-4", name: "T. Rozier", number: "2", position: "PG", stats: { points: 12, rebounds: 2, assists: 6, steals: 1, blocks: 0, turnovers: 2 } },
        { id: "p-mia-5", name: "N. Jovic", number: "5", position: "PF", stats: { points: 7, rebounds: 4, assists: 1, steals: 0, blocks: 1, turnovers: 0 } },
        { id: "p-mia-6", name: "C. Martin", number: "16", position: "SF", stats: { points: 5, rebounds: 3, assists: 1, steals: 1, blocks: 0, turnovers: 1 } },
        { id: "p-mia-7", name: "D. Robinson", number: "55", position: "SG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-mia-8", name: "H. Highsmith", number: "24", position: "PF", stats: { points: 0, rebounds: 2, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
  },
  {
    id: "nba-2",
    league: "nba",
    startTime: "8:00 PM ET",
    status: "scheduled",
    homeTeam: {
      id: "nyk",
      name: "New York",
      abbreviation: "NYK",
      score: null,
      players: [
        { id: "p-nyk-1", name: "J. Brunson", number: "11", position: "PG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-2", name: "J. Randle", number: "30", position: "PF", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-3", name: "OG Anunoby", number: "8", position: "SF", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-4", name: "D. DiVincenzo", number: "0", position: "SG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-5", name: "I. Hartenstein", number: "55", position: "C", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-6", name: "J. Hart", number: "3", position: "SF", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-7", name: "M. Robinson", number: "23", position: "C", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-nyk-8", name: "M. McBride", number: "2", position: "PG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
    awayTeam: {
      id: "phi",
      name: "Philadelphia",
      abbreviation: "PHI",
      score: null,
      players: [
        { id: "p-phi-1", name: "J. Embiid", number: "21", position: "C", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-2", name: "T. Maxey", number: "0", position: "PG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-3", name: "T. Harris", number: "12", position: "PF", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-4", name: "K. Oubre Jr.", number: "9", position: "SF", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-5", name: "N. Batum", number: "40", position: "SF", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-6", name: "B. Hield", number: "17", position: "SG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-7", name: "P. Reed", number: "44", position: "C", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-phi-8", name: "C. Payne", number: "22", position: "PG", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
  },
  {
    id: "nba-3",
    league: "nba",
    startTime: "10:00 PM ET",
    status: "final",
    homeTeam: {
      id: "den",
      name: "Denver",
      abbreviation: "DEN",
      score: 112,
      players: [
        { id: "p-den-1", name: "N. Jokic", number: "15", position: "C", stats: { points: 28, rebounds: 14, assists: 11, steals: 1, blocks: 1, turnovers: 3 } },
        { id: "p-den-2", name: "J. Murray", number: "27", position: "PG", stats: { points: 22, rebounds: 4, assists: 8, steals: 2, blocks: 0, turnovers: 2 } },
        { id: "p-den-3", name: "M. Porter Jr.", number: "1", position: "SF", stats: { points: 19, rebounds: 7, assists: 1, steals: 0, blocks: 1, turnovers: 1 } },
        { id: "p-den-4", name: "A. Gordon", number: "50", position: "PF", stats: { points: 14, rebounds: 8, assists: 4, steals: 1, blocks: 2, turnovers: 1 } },
        { id: "p-den-5", name: "K. Caldwell-Pope", number: "5", position: "SG", stats: { points: 11, rebounds: 2, assists: 3, steals: 2, blocks: 0, turnovers: 0 } },
        { id: "p-den-6", name: "R. Jackson", number: "7", position: "PG", stats: { points: 8, rebounds: 1, assists: 3, steals: 0, blocks: 0, turnovers: 1 } },
        { id: "p-den-7", name: "C. Braun", number: "0", position: "SG", stats: { points: 6, rebounds: 3, assists: 1, steals: 1, blocks: 0, turnovers: 0 } },
        { id: "p-den-8", name: "P. Watson", number: "8", position: "SF", stats: { points: 4, rebounds: 2, assists: 0, steals: 0, blocks: 1, turnovers: 0 } },
      ],
    },
    awayTeam: {
      id: "lal",
      name: "LA Lakers",
      abbreviation: "LAL",
      score: 105,
      players: [
        { id: "p-lal-1", name: "L. James", number: "23", position: "SF", stats: { points: 26, rebounds: 8, assists: 9, steals: 1, blocks: 1, turnovers: 4 } },
        { id: "p-lal-2", name: "A. Davis", number: "3", position: "C", stats: { points: 24, rebounds: 12, assists: 3, steals: 1, blocks: 3, turnovers: 2 } },
        { id: "p-lal-3", name: "D. Russell", number: "1", position: "PG", stats: { points: 16, rebounds: 3, assists: 6, steals: 0, blocks: 0, turnovers: 3 } },
        { id: "p-lal-4", name: "A. Reaves", number: "15", position: "SG", stats: { points: 14, rebounds: 4, assists: 5, steals: 1, blocks: 0, turnovers: 1 } },
        { id: "p-lal-5", name: "R. Hachimura", number: "28", position: "PF", stats: { points: 12, rebounds: 5, assists: 1, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-lal-6", name: "S. Dinwiddie", number: "26", position: "PG", stats: { points: 8, rebounds: 2, assists: 3, steals: 0, blocks: 0, turnovers: 1 } },
        { id: "p-lal-7", name: "T. Prince", number: "12", position: "SF", stats: { points: 5, rebounds: 3, assists: 0, steals: 1, blocks: 0, turnovers: 0 } },
        { id: "p-lal-8", name: "J. Hayes", number: "11", position: "C", stats: { points: 0, rebounds: 2, assists: 0, steals: 0, blocks: 1, turnovers: 0 } },
      ],
    },
  },
];
