import { Game } from "../types";

export const wnbaGames: Game[] = [
  {
    id: "wnba-1",
    league: "wnba",
    startTime: "7:00 PM ET",
    status: "final",
    homeTeam: {
      id: "ny",
      name: "New York",
      abbreviation: "NYL",
      score: 88,
      players: [
        { id: "p-ny-1", name: "B. Stewart", number: "30", position: "PF", stats: { points: 22, rebounds: 10, assists: 4, steals: 2, blocks: 2, turnovers: 2 } },
        { id: "p-ny-2", name: "S. Ionescu", number: "20", position: "G", stats: { points: 18, rebounds: 5, assists: 8, steals: 1, blocks: 0, turnovers: 3 } },
        { id: "p-ny-3", name: "J. Jones", number: "35", position: "C", stats: { points: 14, rebounds: 12, assists: 2, steals: 0, blocks: 1, turnovers: 1 } },
        { id: "p-ny-4", name: "B. Laney-Hamilton", number: "44", position: "G", stats: { points: 12, rebounds: 4, assists: 3, steals: 1, blocks: 0, turnovers: 1 } },
        { id: "p-ny-5", name: "C. Vandersloot", number: "22", position: "G", stats: { points: 8, rebounds: 3, assists: 9, steals: 2, blocks: 0, turnovers: 2 } },
        { id: "p-ny-6", name: "K. Thornton", number: "13", position: "F", stats: { points: 7, rebounds: 4, assists: 1, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-ny-7", name: "N. Sabally", number: "5", position: "F", stats: { points: 4, rebounds: 2, assists: 0, steals: 0, blocks: 1, turnovers: 1 } },
        { id: "p-ny-8", name: "K. Burke", number: "2", position: "G", stats: { points: 3, rebounds: 1, assists: 1, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
    awayTeam: {
      id: "lv",
      name: "Las Vegas",
      abbreviation: "LVA",
      score: 84,
      players: [
        { id: "p-lv-1", name: "A. Wilson", number: "22", position: "C", stats: { points: 26, rebounds: 11, assists: 2, steals: 1, blocks: 3, turnovers: 2 } },
        { id: "p-lv-2", name: "K. Plum", number: "10", position: "G", stats: { points: 19, rebounds: 2, assists: 5, steals: 1, blocks: 0, turnovers: 3 } },
        { id: "p-lv-3", name: "J. Young", number: "0", position: "G", stats: { points: 16, rebounds: 4, assists: 4, steals: 2, blocks: 0, turnovers: 1 } },
        { id: "p-lv-4", name: "C. Gray", number: "12", position: "G", stats: { points: 10, rebounds: 3, assists: 7, steals: 1, blocks: 0, turnovers: 2 } },
        { id: "p-lv-5", name: "A. Clark", number: "20", position: "F", stats: { points: 8, rebounds: 6, assists: 1, steals: 2, blocks: 0, turnovers: 0 } },
        { id: "p-lv-6", name: "K. Stokes", number: "41", position: "C", stats: { points: 2, rebounds: 5, assists: 0, steals: 0, blocks: 1, turnovers: 0 } },
        { id: "p-lv-7", name: "S. George", number: "1", position: "F", stats: { points: 3, rebounds: 1, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-lv-8", name: "A. Hayes", number: "3", position: "C", stats: { points: 0, rebounds: 2, assists: 0, steals: 0, blocks: 0, turnovers: 1 } },
      ],
    },
  },
  {
    id: "wnba-2",
    league: "wnba",
    startTime: "8:00 PM ET",
    status: "in_progress",
    period: "Q2",
    clock: "6:45",
    homeTeam: {
      id: "sea",
      name: "Seattle",
      abbreviation: "SEA",
      score: 34,
      players: [
        { id: "p-sea-1", name: "J. Loyd", number: "24", position: "G", stats: { points: 12, rebounds: 2, assists: 2, steals: 0, blocks: 0, turnovers: 1 } },
        { id: "p-sea-2", name: "N. Ogwumike", number: "30", position: "F", stats: { points: 8, rebounds: 5, assists: 1, steals: 1, blocks: 1, turnovers: 0 } },
        { id: "p-sea-3", name: "S. Diggins-Smith", number: "4", position: "G", stats: { points: 6, rebounds: 1, assists: 4, steals: 0, blocks: 0, turnovers: 1 } },
        { id: "p-sea-4", name: "E. Magbegor", number: "13", position: "C", stats: { points: 4, rebounds: 4, assists: 1, steals: 0, blocks: 2, turnovers: 0 } },
        { id: "p-sea-5", name: "J. Horston", number: "8", position: "G", stats: { points: 4, rebounds: 2, assists: 0, steals: 1, blocks: 0, turnovers: 0 } },
        { id: "p-sea-6", name: "S. Whitcomb", number: "32", position: "G", stats: { points: 0, rebounds: 0, assists: 1, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-sea-7", name: "M. Russell", number: "21", position: "C", stats: { points: 0, rebounds: 1, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-sea-8", name: "V. Vivians", number: "35", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
    awayTeam: {
      id: "ind",
      name: "Indiana",
      abbreviation: "IND",
      score: 32,
      players: [
        { id: "p-ind-1", name: "C. Clark", number: "22", position: "G", stats: { points: 11, rebounds: 3, assists: 4, steals: 0, blocks: 0, turnovers: 2 } },
        { id: "p-ind-2", name: "A. Boston", number: "7", position: "C", stats: { points: 8, rebounds: 6, assists: 1, steals: 0, blocks: 1, turnovers: 0 } },
        { id: "p-ind-3", name: "K. Mitchell", number: "0", position: "G", stats: { points: 7, rebounds: 1, assists: 0, steals: 1, blocks: 0, turnovers: 1 } },
        { id: "p-ind-4", name: "N. Smith", number: "1", position: "F", stats: { points: 4, rebounds: 3, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-ind-5", name: "K. Samuelson", number: "33", position: "F", stats: { points: 2, rebounds: 1, assists: 1, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-ind-6", name: "L. Hull", number: "10", position: "G", stats: { points: 0, rebounds: 0, assists: 1, steals: 1, blocks: 0, turnovers: 0 } },
        { id: "p-ind-7", name: "T. Fagbenle", number: "14", position: "F", stats: { points: 0, rebounds: 2, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-ind-8", name: "K. Wallace", number: "17", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
  },
  {
    id: "wnba-3",
    league: "wnba",
    startTime: "10:00 PM ET",
    status: "scheduled",
    homeTeam: {
      id: "pho",
      name: "Phoenix",
      abbreviation: "PHO",
      score: null,
      players: [
        { id: "p-pho-1", name: "K. Copper", number: "2", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-2", name: "B. Griner", number: "42", position: "C", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-3", name: "D. Taurasi", number: "3", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-4", name: "N. Cloud", number: "0", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-5", name: "R. Allen", number: "9", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-6", name: "S. Cunningham", number: "12", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-7", name: "M. Mack", number: "11", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-pho-8", name: "S. Sutton", number: "1", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
    awayTeam: {
      id: "min",
      name: "Minnesota",
      abbreviation: "MIN",
      score: null,
      players: [
        { id: "p-min-1", name: "N. Collier", number: "24", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-2", name: "K. McBride", number: "21", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-3", name: "C. Williams", number: "10", position: "G", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-4", name: "A. Smith", number: "8", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-5", name: "B. Carleton", number: "6", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-6", name: "N. Hines-Allen", number: "2", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-7", name: "C. Zandalasini", number: "9", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
        { id: "p-min-8", name: "D. Dantas", number: "14", position: "F", stats: { points: 0, rebounds: 0, assists: 0, steals: 0, blocks: 0, turnovers: 0 } },
      ],
    },
  },
];
